package com.pharmeasy.fetchr.type

enum class ItemStatus {
    IN_PROGRESS, PENDING, CREATED, IN_ISSUE, READY_FOR_PUTAWAY, LIVE,
    READY_FOR_PICKING, IN_TRAY, ASSIGNED, PICKED, DONE, IN_USE, FREE, DELETE, COMPLETED, COMPLETED_WITH_ISSUE;
}
