package com.pharmeasy.fetchr.type

enum class Source {
    INVOICE, VERIFIER_ISSUE, RACKER_ISSUE, RETURN, VERIFIER_TASK, RACKER_TASK, AUDITOR_TASK, SALE_RETURN, RECTIFICATION,INVOICE_PROCUREMENT,
    INVOICE_JIT,
}
