package com.pharmeasy.fetchr.type

enum class TaskStatus {
    CREATED, IN_PROGRESS,LIVE, READY_FOR_PUTAWAY, ASSIGNED, PICKED, PENDING_WITH_ISSUE, COMPLETED, RETURNED,
    BILLING_IN_PROGRESS, PENDING_FOR_BILLING, CANCELLED_PENDING_FOR_RETURN, CANCELLED, RETURN_PENDING_WITH_PICKER,
    VERIFIED, RECEIVED, SIDELINED, SIDELINED_ASSIGNED, SIDELINED_ZONE, CANCELLED_ZONE, JIT_ZONE, PROCUREMENT_ZONE,
    SALE_RETURN_ZONE, AUDITOR_ZONE, RECTIFICATION_ZONE, BILLER_ZONE, JIT_BIN_ZONE
}
